### PR TITLE
Bump pathwatcher version to fix installation issues #45 and #47

### PR DESCRIPTION
**Pull request by kaidokert**

### CODE REVIEW

**Comment by LinusU** [comment]
@danielgtaylor Could we get this merged? :+1:

**Comment by ianbytchek** [comment]
@danielgtaylor ping!

**Comment by rdastsm** [comment]
@danielgtaylor looking forward to this 😄 :+1:

**Comment by brentmulligan** [comment]
@danielgtaylor 🙏

**Comment by jsonfry** [comment]
Yes please.

**Comment by zdne** [comment]
@danielgtaylor bump :+1:

**Pull request merged**
